import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { Providers } from "@/components/providers";

import { DynamicBreadcrumbs } from "@/components/dynamic-breadcrumbs";
import ReportIssueButton from "@/components/report-issue-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers> 
          <SidebarProvider> 
            <AppSidebar /> 
            <main className="flex-1 overflow-auto px-4 grid grid-rows-[auto_1fr] transition-all duration-300 ease-in-out"> 
              <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                <div className="flex items-center gap-2 grow">
                  <SidebarTrigger className="-ml-1" /> 
                  <DynamicBreadcrumbs />
                </div>
                <div className="ml-auto flex items-center gap-2">
                  <ReportIssueButton />
                </div>
              </header>
              <div className="mb-4 overflow-auto">
                {children}
              </div>
            </main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
